"""add school overview fields

Revision ID: 215bcb10a81f
Revises: ae5b2d8ced2c
Create Date: 2026-03-20 21:27:34.212751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '215bcb10a81f'
down_revision: Union[str, Sequence[str], None] = 'ae5b2d8ced2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('schools', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('schools', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('established_year', sa.Integer(), nullable=True))
    op.add_column(
        'schools',
        sa.Column('total_classrooms', sa.Integer(), nullable=False, server_default=sa.text('0'))
    )
    op.add_column(
        'schools',
        sa.Column('has_electricity', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        'schools',
        sa.Column('has_water', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('schools', 'total_classrooms', server_default=None)
    op.alter_column('schools', 'has_electricity', server_default=None)
    op.alter_column('schools', 'has_water', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'has_water')
    op.drop_column('schools', 'has_electricity')
    op.drop_column('schools', 'total_classrooms')
    op.drop_column('schools', 'established_year')
    op.drop_column('schools', 'website')
    op.drop_column('schools', 'email')
    op.drop_column('schools', 'phone')
    op.drop_column('schools', 'description')
    # ### end Alembic commands ###
