"""create schools table

Revision ID: 24e301a8b9c6
Revises: 
Create Date: 2026-03-20 02:13:46.606806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '24e301a8b9c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('emis_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('upazila', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('total_teachers', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_district'), 'schools', ['district'], unique=False)
    op.create_index(op.f('ix_schools_emis_code'), 'schools', ['emis_code'], unique=True)
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.drop_index(op.f('ix_schools_emis_code'), table_name='schools')
    op.drop_index(op.f('ix_schools_district'), table_name='schools')
    op.drop_table('schools')
    # ### end Alembic commands ###
