"""add location filters

Revision ID: 5abe5adae743
Revises: 24e301a8b9c6
Create Date: 2026-03-20 03:33:44.057785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '5abe5adae743'
down_revision: Union[str, Sequence[str], None] = '24e301a8b9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('union', sa.String(length=100), nullable=True))
    op.create_index('ix_schools_district_upazila', 'schools', ['district', 'upazila'], unique=False)
    op.create_index(op.f('ix_schools_division'), 'schools', ['division'], unique=False)
    op.create_index('ix_schools_name_trgm', 'schools', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_schools_union'), 'schools', ['union'], unique=False)
    op.create_index(op.f('ix_schools_upazila'), 'schools', ['upazila'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schools_upazila'), table_name='schools')
    op.drop_index(op.f('ix_schools_union'), table_name='schools')
    op.drop_index('ix_schools_name_trgm', table_name='schools', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_schools_division'), table_name='schools')
    op.drop_index('ix_schools_district_upazila', table_name='schools')
    op.drop_column('schools', 'union')
    # ### end Alembic commands ###
