"""add student stats to schools

Revision ID: a6fbc65af843
Revises: 520c794450f0
Create Date: 2026-03-21 12:41:54.678470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'a6fbc65af843'
down_revision: Union[str, Sequence[str], None] = '520c794450f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'schools',
        sa.Column('boys', sa.Integer(), nullable=False, server_default=sa.text('0'))
    )
    op.add_column(
        'schools',
        sa.Column('girls', sa.Integer(), nullable=False, server_default=sa.text('0'))
    )
    op.alter_column('schools', 'boys', server_default=None)
    op.alter_column('schools', 'girls', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'girls')
    op.drop_column('schools', 'boys')
    # ### end Alembic commands ###
