"""add country_code to schools

Revision ID: ae5b2d8ced2c
Revises: 5abe5adae743
Create Date: 2026-03-20 15:23:45.594536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ae5b2d8ced2c'
down_revision: Union[str, Sequence[str], None] = '5abe5adae743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schools",
        sa.Column("country_code", sa.String(), nullable=False, server_default="BD")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schools", "country_code")
    # ### end Alembic commands ###
